name: Check Styling

on: [push]

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: mbstring, pdo, pdo_sqlite, openssl
          coverage: none

      - name: Install dependencies
        run: composer install

      - name: run PHP CS Fixer
        run: vendor/bin/php-cs-fixer fix --diff --dry-run
