name: Psalm Analyze

on: [push, pull_request]

jobs:
  psalm:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: ['8.3', '8.4', '8.5']

    name: P${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build containers
        run: docker compose build --build-arg PHP_VERSION=${{ matrix.php }}

      - name: Start services
        run: docker compose up -d

      - name: Install dependencies
        run: docker compose exec php composer update --prefer-dist --no-interaction

      - name: Run Psalm
        run: docker compose exec php vendor/bin/psalm

      - name: Stop services
        if: always()
        run: docker compose down
